spring.application.name=slaughter-house

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=slaughterhouse
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# SQL init (odpali schema.sql i data.sql)
spring.sql.init.mode=always

# gRPC
grpc.server.port=9090

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:pro3.p12
server.ssl.key-store-password=Skajblok2411!

server.ssl.keyStoreType=PKCS12
server.ssl.keyStoreProvider=SUN

